const actionTypes = {
    GET_LOCATIONS: "GET_LOCATIONS",
    GET_LOCATIONS_LOADING: "GET_LOCATIONS_LOADING",
    GET_LOCATIONS_ERROR: "GET_LOCATIONS_ERROR",
    GET_LOCATIONS_SUCCESS: "GET_LOCATIONS_SUCCESS"
};

export default actionTypes;
