const actionTypes = {
    TOGGLE_MONITORING_POINT: "TOGGLE_MONITORING_POINT",
    MONITORING_POINT_INFO: "MONITORING_POINT_INFO",
    VISIBLE_MONITORING_INFO: "VISIBLE_MONITORING_INFO",
    MONITORING_POINT_NAME: "MONITORING_POINT_NAME"
};

export default actionTypes;
