const actionTypes = {
    GET_WATER_LEVELS: "GET_WATER_LEVELS",
    GET_WATER_LEVELS_LOADING: "GET_WATER_LEVELS_LOADING",
    GET_WATER_LEVELS_ERROR: "GET_WATER_LEVELS_ERROR",
    GET_WATER_LEVELS_SUCCESS: "GET_WATER_LEVELS_SUCCESS",

    GET_GW: "GET_GW"
};

export default actionTypes;
